config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users do
    resources :feed_items
  end
end

app/models/feed_item.rb
class FeedItem < ActiveRecord::Base

  belongs_to :user

  def uid
    user.uid
  end

  def file_date
    published.strftime
  end

  def file_title
    title.parameterize
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :feed_items

  def feed
    "https://audioboom.com/users/#{uid}/boos.rss"
  end

  validates :uid, presence: true
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feed_item_controller.rb
class FeedItemController < ApplicationController
  def index
    user = User.find(params[:user_id])
    @feed_items = user.feed_items
  end

  def show
    user = User.find(params[:user_id])
    @feed_item = user.feed_items.find(params[:id])
  end
end

app/controllers/feed_items_controller.rb
class FeedItemsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @feed_items = @user.feed_items
    respond_to do |format|
      format.html
      format.rss { render layout: false }
    end
  end

  def show
    @user = User.find(params[:user_id])
    @feed_item = @user.feed_items.find(params[:id])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_item_helper.rb
module FeedItemHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/feed_items/index.html.erb
<table>
  <thead>
    <tr>
      <th width="200">title</th>
      <th width="200">published</th>
    </tr>
  </thead>
  <tbody>
  	 <% @feed_items.each do |feed_item| %>
  	 <tr>
  	 	<td><%= link_to feed_item.title, feed_item.link %></td>
  	 	<td><%= feed_item.published.strftime %></td>
  	 </tr>
  	 <% end %>
  </tbody>
 </table>

app/views/feed_items/show.html.erb
<h1>FeedItem#show</h1>
<p>Find me in app/views/feed_item/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>badaboom</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	 <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1 id="status">badaboom!</h1>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "home", root_path %></li>
        </ul>
    </div>
  </nav>
    <div class="row">
      <div class="large-8 columns">
        <%= yield %>
      </div>
      <div class="large-4 columns">
        <h3 class="subheader">death to audioboom</h3>
        <p>We use pusher to update the front end! Current status:
        <span id="connection_state" class="subheader">&dash;</span></p>
      </div>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>User#edit</h1>
<p>Find me in app/views/user/edit.html.erb</p>

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th width="200">username</th>
      <th width="200">audioboo(m) URL</th>
      <th width="200">boos</th>
      <th width="200">feed page</th>
    </tr>
  </thead>
  <tbody>
  	 <% @users.each do |user| %>
  	 <tr>
  	 	<td><%= link_to user.username, user_feed_items_path(user) %></td>
  	 	<td><%= link_to user.feed, user.feed %></td>
  	 	<td id="feed_items_<%= user.uid %>"><%= user.feed_items.count %></td>
  	 	<td><%= link_to 'feed', user_feed_items_path(user, format: :rss) unless user.feed_items.empty? %></td>
  	 </tr>
  	 <% end %>
  </tbody>
 </table>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/show.html.erb
 <div class="row header"><%= @user.username %></div>
<p><%= link_to 'audioboo feed', @user.feed %></p>

app/views/users/update.html.erb
<h1>User#update</h1>
<p>Find me in app/views/user/update.html.erb</p>